# Common settings
[common]
http_timeout=60
#update_tag="<CHANGEME>"
[neo4j]
uri="bolt://localhost:7687"
#user="neo4j"
#password="neo4j"
password_prompt=false
max_connection_lifetime=3600
database="neo4j"
[analysis]
#job_directory
[bigfix]
#username=""
#password=""
#root_url=""
[crowdstrike]
#client_id=""
#client_secret=""
#api_url=""
[cve]
#enabled=true
#url="https://services.nvd.nist.gov/rest/json/cves/2.0/"
#api_key=""
[digitalocean]
#token=""
[duo]
#api_key=""
#api_secret=""
#api_hostname=""
[jamf]
#base_url=""
#user=""
#password=""
[kandji]
#base_url=""
#tenant_id=""
#token=""
[lastpass]
#cid=""
#provhash=""
[okta]
#saml_role_regex="^aws\#\S+\#(?{{role}}[\w\-]+)\#(?{{accountid}}\d+)$"
#api_key=""
#org_id=""
[pagerduty]
#api_key=""
[semgrep]
#token=""
#dependency_ecosystems="gomod,npm,pypi"
[snipeit]
#base_url=""
#token=""
#tenant_id=""
